# See https://pre-commit.com/hooks.html for more information
# See https://pre-commit.com/docs/repositories_for_policies.html for more information

default_language_version:
    python: python3

repos:
  - repo: local
    hooks:
      - id: markdownlint-commit
        name: Markdown lint (lightweight)
        entry: bash -lc 'LINT_ONLY=true LINT_FALLBACK_OK=true SKIP_PANDOC=true VALIDATE_MERMAID=skip bash scripts/validate-md.sh'
        language: system
        files: ^doc/.*\.md$
        pass_filenames: false
      - id: ruff-format
        name: Ruff Format
        entry: ruff format --check .
        language: system
        pass_filenames: false
      - id: ruff
        name: Ruff Lint
        entry: ruff check .
        language: system
        pass_filenames: false
      - id: mypy
        name: Mypy Type Check
        entry: mypy .
        language: system
        pass_filenames: false
      - id: validate-md
        name: Validate Markdown and Mermaid
        entry: bash -lc 'VALIDATE_MERMAID=warn_on_sandbox bash scripts/validate-md.sh'
        language: system
        files: ^doc/.*\.md$
        pass_filenames: true
        stages: [pre-push]
      - id: pytest
        name: Run unit tests (pytest -q)
        entry: pytest -q
        language: system
        pass_filenames: false
        stages: [pre-commit]
