name: Lint and Type Check

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ "**" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]
      - name: Ruff Format (check only)
        run: |
          ruff format --check .
      - name: Ruff Lint
        run: |
          ruff check .
      - name: Mypy
        run: |
          mypy .
