name: pre-commit

on:
  pull_request:
  push:
    branches: [ main, master ]

jobs:
  run-pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install Python dev deps
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]
      - name: Install pandoc (for doc validation)
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc
      - name: Setup Node and install Mermaid/markdownlint
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install Mermaid and markdownlint
        run: |
          npm install -g @mermaid-js/mermaid-cli markdownlint-cli
      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1
